name = "fftpack-5"
version = "0.1"
license = "MIT" 	# Follow the `forlab` license
author = "keurfonluu"
maintainer = "keurfon.luu@mines-paristech.fr"
copyright = "2016-2021 fftpack contributors"

[library]
source-dir="src"

[dependencies]
forlab = { git = "https://github.com/zoziha/forlab.git" }

[[test]]
name="example_fft"
source-dir="test"
main="example_fft.f90"
